/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-tertiary": "#ffffff",
        "tertiary-fixed": "#e1e0ff",
        "on-secondary-fixed": "#2a1700",
        "background": "#faf8ff",
        "error": "#ba1a1a",
        "tertiary-container": "#6063ee",
        "on-tertiary-container": "#fffbff",
        "on-background": "#131b2e",
        "primary-container": "#2170e4",
        "surface-dim": "#d2d9f4",
        "inverse-primary": "#adc6ff",
        "on-primary": "#ffffff",
        "on-secondary-container": "#684000",
        "primary-fixed": "#d8e2ff",
        "on-surface": "#131b2e",
        "tertiary": "#4648d4",
        "surface": "#faf8ff",
        "primary": "#0058be",
        "on-primary-container": "#fefcff",
        "tertiary-fixed-dim": "#c0c1ff",
        "surface-container": "#eaedff",
        "surface-variant": "#dae2fd",
        "surface-container-low": "#f2f3ff",
        "secondary": "#855300",
        "surface-container-high": "#e2e7ff",
        "on-error-container": "#93000a",
        "on-secondary-fixed-variant": "#653e00",
        "outline": "#727785",
        "on-tertiary-fixed-variant": "#2f2ebe",
        "inverse-surface": "#283044",
        "surface-tint": "#005ac2",
        "surface-container-highest": "#dae2fd",
        "inverse-on-surface": "#eef0ff",
        "on-error": "#ffffff",
        "secondary-container": "#fea619",
        "primary-fixed-dim": "#adc6ff",
        "surface-bright": "#faf8ff",
        "on-tertiary-fixed": "#07006c",
        "outline-variant": "#c2c6d6",
        "on-primary-fixed": "#001a42",
        "error-container": "#ffdad6",
        "secondary-fixed-dim": "#ffb95f",
        "on-surface-variant": "#424754",
        "on-secondary": "#ffffff",
        "surface-container-lowest": "#ffffff",
        "on-primary-fixed-variant": "#004395",
        "secondary-fixed": "#ffddb8"
      },
      borderRadius: {
        "DEFAULT": "1rem",
        "lg": "2rem",
        "xl": "3rem",
        "full": "9999px"
      },
      spacing: {
        "stack-sm": "0.5rem",
        "container-padding-desktop": "2.5rem",
        "stack-lg": "2rem",
        "base": "8px",
        "stack-md": "1rem",
        "container-padding-mobile": "1.25rem",
        "gutter": "1.5rem"
      },
      fontFamily: {
        "headline-lg-mobile": ["Plus Jakarta Sans", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "headline-md": ["Plus Jakarta Sans", "sans-serif"],
        "display-lg": ["Plus Jakarta Sans", "sans-serif"],
        "headline-lg": ["Plus Jakarta Sans", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "label-md": ["JetBrains Mono", "monospace"],
        "body-lg": ["Inter", "sans-serif"],
        "button": ["Plus Jakarta Sans", "sans-serif"]
      },
      fontSize: {
        "headline-lg-mobile": ["24px", { lineHeight: "1.2", fontWeight: "600" }],
        "body-md": ["16px", { lineHeight: "1.5", fontWeight: "400" }],
        "headline-md": ["24px", { lineHeight: "1.3", fontWeight: "600" }],
        "display-lg": ["48px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-lg": ["32px", { lineHeight: "1.2", letterSpacing: "-0.01em", fontWeight: "600" }],
        "body-sm": ["14px", { lineHeight: "1.5", fontWeight: "400" }],
        "label-md": ["13px", { lineHeight: "1.0", letterSpacing: "0.05em", fontWeight: "500" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "button": ["15px", { lineHeight: "1.0", fontWeight: "600" }]
      }
    }
  },
  plugins: [],
}
