import { jsPDF } from 'jspdf';
import autoTable from 'jspdf-autotable';

const ACTION_LABELS = {
  REJECT_FREEZE_TRANSACTION: 'Reject & Freeze Transaction',
  ESCALATE_TO_COMMITTEE: 'Escalate to Committee',
  EXPORT_AUDIT_DOSSIER: 'Audit Dossier Exported',
};

export function actionLabel(action) {
  if (!action) return 'Compliance Decision';
  if (ACTION_LABELS[action]) return ACTION_LABELS[action];
  return action
    .replace(/_/g, ' ')
    .toLowerCase()
    .replace(/\b\w/g, (ch) => ch.toUpperCase());
}

export function formatTicket(id) {
  return `SV-${1000 + id}`;
}

// Renders every recorded compliance decision into a downloadable dossier PDF.
export function exportAuditDossier(actions, investigator = {}) {
  const rows = (actions || []).map((a) => [
    formatTicket(a.id),
    a.entity_name || a.entity_id || '—',
    actionLabel(a.action),
    String(a.created_at || ''),
  ]);

  const doc = new jsPDF();

  doc.setFillColor(19, 27, 46);
  doc.rect(0, 0, 210, 30, 'F');
  doc.setTextColor(255, 255, 255);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(16);
  doc.text('Argus - Compliance Audit Dossier', 14, 13);
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9);
  const jurisdiction = investigator.homeCountryName
    ? `Investigator jurisdiction: ${investigator.homeCountryName}`
    : '';
  doc.text(`Generated ${new Date().toLocaleString()}${jurisdiction ? ` | ${jurisdiction}` : ''}`, 14, 21);

  autoTable(doc, {
    startY: 38,
    head: [['Ticket', 'Entity', 'Action', 'Logged At (UTC)']],
    body: rows.length ? rows : [['—', '—', 'No decisions recorded', '—']],
    styles: { fontSize: 8, cellPadding: 2.5 },
    headStyles: { fillColor: [33, 112, 228] },
    alternateRowStyles: { fillColor: [244, 246, 250] },
  });

  const finalY = doc.lastAutoTable?.finalY || 40;
  doc.setFontSize(8);
  doc.setTextColor(110);
  doc.text(
    `${rows.length} compliance decision(s) on file. Generated by the Argus bilateral sanctions & adverse-media intelligence pipeline.`,
    14,
    finalY + 10
  );

  const ts = new Date().toISOString().slice(0, 16).replace(/[:T]/g, '-');
  doc.save(`argus-audit-dossier-${ts}.pdf`);
}
